image: registry.gitlab.com/islandoftex/images/texlive:latest

default:
  tags:
    - gitlab-org-docker

build:
  script:
    - for dir in latex/resumes/*/ ; do (cd "$dir" && lualatex main.tex); done
  artifacts:
    paths:
      - latex/resumes/**/*.pdf
      - latex/cover/**/*.pdf
  only:
    - main