---
name: Build application
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  resume:
    name: Build application
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build
        run: |
          for dir in latex/resumes/*/; do
            [ -d "$dir" ] || continue
            echo "Building $dir"
            (cd "$dir" && lualatex main.tex)
          done
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          path: ./latex/resumes/*/*.pdf
          retention-days: 30
